### ISSUE TITLE
Running `dotnet run` on `http` project errors with "Cannot enable wasi-http for core wasm modules"

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [dev-wasm/dev-wasm-dotnet#6]
Tried on both local (MacOS M1) & GitHub Codespaces. Am I doing something wrong?

**Comment by brendandburns** [comment]
@Zhiyuan-Amos I fixed this, with a newer `wasmtime` you need the instruction here:
https://github.com/dev-wasm/dev-wasm-dotnet/blob/main/http/http.csproj#L12

or here:
https://github.com/dev-wasm/dev-wasm-dotnet/blob/main/www-wasi/Makefile#L17
